
#--------------------------------------------------------------------------------
# values.yml : Set of values commonly overridden in microservices
# 			   The file can be extended with other elements, as necessary
#--------------------------------------------------------------------------------

# client.yml
client.timeout: 3000
client.verifyHostname: false

# server.yml
server.httpsPort: 9443
server.enableHttp: false
server.enableHttps: true
server.enableHttp2: true
server.enableRegistry: true
server.serviceId: com.networknt.petstore-3.1.0
server.environment: dev
server.buildNumber: 3.1.0
# security.yml
security.enableVerifyJwt: false

# metrics.yml
metrics.enabled: false

# service.yml
service.singletons:
- com.networknt.registry.URL:
  - com.networknt.registry.URLImpl
- com.networknt.portal.registry.client.PortalRegistryClient:
  - com.networknt.portal.registry.client.PortalRegistryClientImpl
- com.networknt.registry.Registry:
  - com.networknt.portal.registry.PortalRegistry
- com.networknt.balance.LoadBalance:
  - com.networknt.balance.RoundRobinLoadBalance
- com.networknt.cluster.Cluster:
  - com.networknt.cluster.LightCluster
- com.networknt.cache.CacheManager:
  - com.networknt.cache.CaffeineCacheManager
# StartupHookProvider implementations, there are one to many and they are called in the same sequence defined.
- com.networknt.server.StartupHookProvider:
  
  
# ShutdownHookProvider implementations, there are one to many and they are called in the same sequence defined.
- com.networknt.server.ShutdownHookProvider:
  
# handler.yml
handler.handlers:
  # Light-framework cross-cutting concerns implemented in the microservice
  - com.networknt.exception.ExceptionHandler@exception
  - com.networknt.metrics.MetricsHandler@metrics
  - com.networknt.traceability.TraceabilityHandler@traceability
  - com.networknt.correlation.CorrelationHandler@correlation
  - com.networknt.openapi.OpenApiHandler@specification
  - com.networknt.openapi.JwtVerifyHandler@security
  - com.networknt.body.BodyHandler@body
  - com.networknt.audit.AuditHandler@audit
  # DumpHandler is to dump detail request/response info to log, useful for troubleshooting but not suggested to use in production due to it may lower the performance
  # - com.networknt.dump.DumpHandler@dump
  - com.networknt.sanitizer.SanitizerHandler@sanitizer
  - com.networknt.openapi.ValidatorHandler@validator
  # Customer business domain specific cross-cutting concerns handlers
  # - com.example.validator.CustomizedValidator@custvalidator
  # Framework endpoint handlers
  - com.networknt.health.HealthGetHandler@health
  - com.networknt.info.ServerInfoGetHandler@info
  - com.networknt.logging.handler.LoggerGetHandler@getLogger
  - com.networknt.logging.handler.LoggerPostHandler@postLogger
  - com.networknt.logging.handler.LoggerGetLogContentsHandler@getLogContents
  - com.networknt.config.reload.handler.ModuleRegistryGetHandler@modules
  - com.networknt.config.reload.handler.ConfigReloadHandler@configReload
  - com.networknt.specification.SpecDisplayHandler@spec
  - com.networknt.specification.SpecSwaggerUIHandler@swaggerui
  # - com.networknt.metrics.prometheus.PrometheusGetHandler@getprometheus
  - com.networknt.server.handler.ServerShutdownHandler@shutdown
  - com.networknt.cache.CacheExplorerHandler@cache
  # Business Handlers
  - com.networknt.petstore.handler.PetsGetHandler
  - com.networknt.petstore.handler.PetsPostHandler
  - com.networknt.petstore.handler.PetsPetIdGetHandler
  - com.networknt.petstore.handler.PetsPetIdPutHandler
  - com.networknt.petstore.handler.PetsPetIdDeleteHandler
  - com.networknt.petstore.handler.AccountsGetHandler
  - com.networknt.petstore.handler.AccountsPostHandler
  - com.networknt.petstore.handler.AccountsAccountNoGetHandler
  - com.networknt.petstore.handler.AccountsAccountNoPutHandler
  - com.networknt.petstore.handler.AccountsAccountNoDeleteHandler
  - com.networknt.petstore.handler.NotificationsGetHandler
  - com.networknt.petstore.handler.FlowersPostHandler
  - com.networknt.petstore.handler.DocumentsGetHandler
  - com.networknt.petstore.handler.StreamsGetHandler

handler.chains:
  default:
    - exception
    - metrics
    - traceability
    - correlation
    - specification
    - security
    - body
    - audit
    - sanitizer
    - validator

handler.paths:
  - path: '/v1/pets'
    method: 'GET'
    exec:
      - default
      - com.networknt.petstore.handler.PetsGetHandler
  - path: '/v1/pets'
    method: 'POST'
    exec:
      - default
      - com.networknt.petstore.handler.PetsPostHandler
  - path: '/v1/pets/{petId}'
    method: 'GET'
    exec:
      - default
      - com.networknt.petstore.handler.PetsPetIdGetHandler
  - path: '/v1/pets/{petId}'
    method: 'PUT'
    exec:
      - default
      - com.networknt.petstore.handler.PetsPetIdPutHandler
  - path: '/v1/pets/{petId}'
    method: 'DELETE'
    exec:
      - default
      - com.networknt.petstore.handler.PetsPetIdDeleteHandler
  - path: '/v1/accounts'
    method: 'GET'
    exec:
      - default
      - com.networknt.petstore.handler.AccountsGetHandler
  - path: '/v1/accounts'
    method: 'POST'
    exec:
      - default
      - com.networknt.petstore.handler.AccountsPostHandler
  - path: '/v1/accounts/{accountNo}'
    method: 'GET'
    exec:
      - default
      - com.networknt.petstore.handler.AccountsAccountNoGetHandler
  - path: '/v1/accounts/{accountNo}'
    method: 'PUT'
    exec:
      - default
      - com.networknt.petstore.handler.AccountsAccountNoPutHandler
  - path: '/v1/accounts/{accountNo}'
    method: 'DELETE'
    exec:
      - default
      - com.networknt.petstore.handler.AccountsAccountNoDeleteHandler
  - path: '/v1/notifications'
    method: 'GET'
    exec:
      - default
      - com.networknt.petstore.handler.NotificationsGetHandler
  - path: '/v1/flowers'
    method: 'POST'
    exec:
      - default
      - com.networknt.petstore.handler.FlowersPostHandler
  - path: '/v1/documents'
    method: 'GET'
    exec:
      - default
      - com.networknt.petstore.handler.DocumentsGetHandler
  - path: '/v1/streams'
    method: 'GET'
    exec:
      - default
      - com.networknt.petstore.handler.StreamsGetHandler


  - path: '/health'
    method: 'get'
    exec:
      - health

  - path: '/adm/health/${server.serviceId:com.networknt.petstore-3.1.0}'
    method: 'get'
    exec:
      - security
      - health

  - path: '/adm/server/info'
    method: 'get'
    exec:
      - security
      - info

  - path: '/adm/logger'
    method: 'get'
    exec:
      - security
      - getLogger

  - path: '/adm/logger'
    method: 'post'
    exec:
      - security
      - body
      - postLogger
  - path: '/adm/logger/content'
    method: 'get'
    exec:
      - security
      - getLogContents

  - path: '/adm/modules'
    method: 'get'
    exec:
      - security
      - modules

  - path: '/adm/modules'
    method: 'post'
    exec:
      - security
      - body
      - configReload

  - path: '/adm/shutdown'
    method: 'delete'
    exec:
      - security
      - shutdown

  - path: '/adm/cache/{name}'
    method: 'get'
    exec:
      - security
      - cache


  - path: '/spec.yaml'
    method: 'get'
    exec:
      - spec
  - path: '/specui.html'
    method: 'get'
    exec:
      - swaggerui


# portal-registry.yml
portalRegistry.portalUrl: https://localhost:8438

# cache.yml
cache.caches:
  - cacheName: jwt
    expiryInMinutes: 15
    maxSize: 100
  - cacheName: jwk
    expiryInMinutes: 129600
    maxSize: 100
