apiVersion: v1
kind: Service
metadata:
  name: ${service.name:openapi-petstore}
  namespace: ${namespace:openapi-petstore}
  labels:
    app.kubernetes.io/name: ${name:openapi-petstore}
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: lightapi
spec:
  type: ${service.type:ClusterIP}
  selector:
    app.kubernetes.io/name: ${name:openapi-petstore}
  ports:
    - name: https
      protocol: TCP
      port: ${service.httpsPort:9445}
      targetPort: sidecar-https
    - name: http
      protocol: TCP
      port: ${service.httpPort:9080}
      targetPort: sidecar-http
